name: uva_robocasa

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchvision=0.16.0

  # Match current RoboCasa requirements
  - numpy=2.2.5
  - numba=0.61.2
  - scipy=1.15.3

  # UVA / training stack
  - pandas
  - ipykernel
  - matplotlib
  - av
  - pyyaml
  - tqdm
  - zarr=2.16
  - numcodecs=0.11
  - hydra-core=1.2.0
  - dill=0.3.7
  - einops=0.6.1
  - diffusers=0.18.2
  - timm=0.9.7
  - cython
  - accelerate=1.0.1
  - boto3
  - aiohttp
  - aiofiles
  - lz4
  - h5py
  - lxml
  - imageio
  - pillow
  - termcolor

  - pip:
      - gdown==5.2.0
      - imagecodecs==2024.12.30
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - opencv-python==4.11.0.86
      - pygame==2.6.1
      - pymunk==6.11.1
      - scikit-image==0.24.0
      - shapely==2.0.7
      - tensorboard==2.19.0
      - transformers==4.28.0
      - huggingface_hub==0.25.2
      - wandb==0.18.3

      # RoboCasa requirements
      - mujoco==3.3.1
      - pynput
      - hidapi
      - tianshou==0.4.10
      - lerobot==0.3.3
      - gymnasium
