name: uva
defaults:
  - _self_
  - task: robocasa/pretrain_human300
  - model: uva


task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 17
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_cond: True

ema:
  _target_: unified_video_action.model.autoregressive.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 32
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False
  # persistent_workers: True # set it to True based on recommendation from perplexity online

val_dataloader:
  batch_size: 32
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  # Transformer needs LR warmup
  lr_warmup_steps: 1000
  num_epochs: 1000
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: null
  checkpoint_every: 50
  val_every: 50
  sample_every: 5
  # steps per epoch
  max_train_steps: 500
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  mixed_precision: 'fp16'

logging:
  project: unified_video_action
  resume: True
  mode: online
  name: train_uva_robocasa_pretrain300
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 20
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False
  

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: train_uva_robocasa_pretrain300
